
name: Construir Flet APK

on:
  # Se ejecuta cada vez que haces push a la rama 'main'
  push:
    branches: [ "main" ] # O "master", si usas esa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Construir app Flet (APK)
        # Esta es una "Action" mágica que Flet provee
        # Instala Python, Flet, Flutter, y todo lo necesario
        uses: flet-dev/flet-build@v1
        with:
          platform: apk
          # Opcional: Si tu 'flet.yml' está en otra ruta, especifícala
          # project_path: . 

          # Opcional: Si quieres pasar la versión desde aquí
          # version: 1.0.0

      - name: Subir APK como Artefacto
        # Este paso toma la APK compilada y la adjunta a la ejecución
        uses: actions/upload-artifact@v4
        with:
          name: gestor-de-laboratorios-apk
          path: build/apk/app-release.apk
