name: Construir Flet APK

on:
  push:
    branches: [ "main" ] # O "master", si usas esa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Construir app Flet (APK)
        # --- ¡AQUÍ ESTÁ LA CORRECCIÓN! ---
        # Usamos una versión específica en lugar de @v1
        uses: flet-dev/flet-build-action@v1.0.3
        with:
          platform: apk
          
      - name: Subir APK como Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: gestor-de-laboratorios-apk
          path: build/apk/app-release.apk
