name: Construir Flet APK (Manual Completo)

on:
  push:
    branches: [ "main" ] # O "master", si usas esa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Flet y dependencias
        run: |
          pip install flet
          # Esta línea es MUY importante que funcione
          pip install -r requirements.txt

      - name: Configurar Flutter SDK (con Subosito)
        # Esta es la acción de la comunidad, es la más popular
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Usamos el canal estable de Flutter

      - name: Aceptar licencias de Android
        run: flutter doctor --android-licenses

      - name: Construir la APK
        run: flet build apk

      - name: Subir APK como Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: gestor-de-laboratorios-apk
          path: build/apk/app-release.apk
